In [2]:
pd.DataFrame([[20,10],[15,30]], columns=['등산', '수영'], index=['남자', '여자'])

    등산  수영
남자  20  10
여자  15  30

In [3]:
import pandas as pd
df5= pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/25/problem5.csv',encoding='cp949')
df5.head(2)

df5_solve=df5

In [4]:
# df5_solve.groupby('공장명')['출하 소요시간'].median()
# df5_solve.groupby('공장명')['출하 소요시간'].count()

import scipy.stats as stats

stats.kruskal(
    df5_solve[df5_solve['공장명']=='X']['출하 소요시간']
    , df5_solve[df5_solve['공장명']=='Y']['출하 소요시간']
    , df5_solve[df5_solve['공장명']=='Z']['출하 소요시간']
)

KruskalResult(statistic=0.7217886080379153, pvalue=0.6970526702392181)

In [6]:
df6 = pd.DataFrame([[10,20,15],[15,14,19],[12,11,30],[13,25,20],[16,30,24]], columns = ['1개년','2개년','3개년'], index=['1안','2안','3안','4안','5안'])

In [ ]:
pd.DataFrame()

In [8]:
df6_solve = df6

df6_solve

    1개년  2개년  3개년
1안   10   20   15
2안   15   14   19
3안   12   11   30
4안   13   25   20
5안   16   30   24

In [ ]:
# from scipy.optimize import linprog

dir(scipy.optimize)

['BFGS',
 'Bounds',
 'HessianUpdateStrategy',
 'LbfgsInvHessProduct',
 'LinearConstraint',
 'NonlinearConstraint',
 'OptimizeResult',
 'OptimizeWarning',
 'RootResults',
 'SR1',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__nnls',
 '__package__',
 '__path__',
 '__spec__',
 '_basinhopping',
 '_bglu_dense',
 '_cobyla',
 '_constraints',
 '_differentiable_functions',
 '_differentialevolution',
 '_dual_annealing',
 '_group_columns',
 '_hessian_update_strategy',
 '_highs',
 '_lbfgsb',
 '_linprog',
 '_linprog_doc',
 '_linprog_highs',
 '_linprog_ip',
 '_linprog_rs',
 '_linprog_simplex',
 '_linprog_util',
 '_lsap',
 '_lsap_module',
 '_lsq',
 '_minimize',
 '_minpack',
 '_nnls',
 '_numdiff',
 '_qap',
 '_remove_redundancy',
 '_root',
 '_root_scalar',
 '_shgo',
 '_shgo_lib',
 '_slsqp',
 '_spectral',
 '_trlib',
 '_trustregion',
 '_trustregion_constr',
 '_trustregion_dogleg',
 '_trustregion_exact',
 '_trustregion_krylov',
 '_trustregion_ncg',
 '_zeros',
 'anderson',
 'approx_fprime',
 'basinhopping',
 'bisect',
 'bracket',
 'brent',
 'brenth',
 'brentq',
 'broyden1',
 'broyden2',
 'brute',
 'check_grad',
 'cobyla',
 'curve_fit',
 'diagbroyden',
 'differential_evolution',
 'dual_annealing',
 'excitingmixing',
 'fixed_point',
 'fmin',
 'fmin_bfgs',
 'fmin_cg',
 'fmin_cobyla',
 'fmin_l_bfgs_b',
 'fmin_ncg',
 'fmin_powell',
 'fmin_slsqp',
 'fmin_tnc',
 'fminbound',
 'fsolve',
 'golden',
 'lbfgsb',
 'least_squares',
 'leastsq',
 'line_search',
 'linear_sum_assignment',
 'linearmixing',
 'linesearch',
 'linprog',
 'linprog_verbose_callback',
 'lsq_linear',
 'minimize',
 'minimize_scalar',
 'minpack',
 'minpack2',
 'moduleTNC',
 'newton',
 'newton_krylov',
 'nnls',
 'nonlin',
 'optimize',
 'quadratic_assignment',
 'ridder',
 'root',
 'root_scalar',
 'rosen',
 'rosen_der',
 'rosen_hess',
 'rosen_hess_prod',
 'shgo',
 'show_options',
 'slsqp',
 'test',
 'tnc',
 'toms748',
 'zeros']