In [1]:
import pandas as pd
df1 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/28/p1.csv')
df1.head(2)

,sex,age,pstatus,medu,fedu,guardian,traveltime,studytime,failures,freetime,famrel,absences
0,F,18,A,4,4,mother,2,2,0,3,4,2
1,F,17,T,1,1,father,1,2,0,3,5,1

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sex         395 non-null    object
 1   age         395 non-null    int64
 2   pstatus     395 non-null    object
 3   medu        395 non-null    int64
 4   fedu        395 non-null    int64
 5   guardian    395 non-null    object
 6   traveltime  395 non-null    int64
 7   studytime   395 non-null    int64
 8   failures    395 non-null    int64
 9   freetime    395 non-null    int64
 10  famrel      395 non-null    int64
 11  absences    395 non-null    int64
dtypes: int64(9), object(3)
memory usage: 37.2+ KB

In [21]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sex         395 non-null    category
 1   age         395 non-null    int64
 2   pstatus     395 non-null    category
 3   medu        0 non-null      category
 4   fedu        0 non-null      category
 5   guardian    395 non-null    category
 6   traveltime  0 non-null      category
 7   studytime   0 non-null      category
 8   failures    0 non-null      category
 9   freetime    0 non-null      category
 10  famrel      0 non-null      category
 11  absences    0 non-null      category
dtypes: category(11), int64(1)
memory usage: 9.3 KB

In [24]:
import pandas_profiling

df1 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/28/p1.csv')

# # ==================================================================================================

# from pandas.api.types import CategoricalDtype
# ordinal_type = CategoricalDtype(categories=['1', '2', '3','4','5'], ordered=True)

# df1[['medu','fedu','traveltime','studytime','failures','freetime','famrel','absences']] = (
#     df1[['medu','fedu','traveltime','studytime','failures','freetime','famrel','absences']].astype(object)
# )

# df1[['medu','fedu','traveltime','studytime','failures','freetime','famrel','absences']] = (
#     df1[['medu','fedu','traveltime','studytime','failures','freetime','famrel','absences']].astype(ordinal_type)
# )

# df1[['sex', 'pstatus', 'guardian']] = df1[['sex', 'pstatus', 'guardian']].astype('category')
# # ==================================================================================================



profile = df1.profile_report(title='temp', correlations={'phi_k':False})

profile

In [44]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/28/p5_.csv')



# df.info()

# df['bf'] = df['data'].str.split('__').str[0]
# df['aft'] = df['data'].str.split('__').str[0]

df['bf'] = df['data'].str.split('__').str[0].str.split('_').str[1].map({'유':1, '무':0})
df['aft'] = df['data'].str.split('__').str[1].str.split('_').str[1].map({'유':1, '무':0})

df.head()

# help(pd.crosstab)

pd.crosstab(index=df['bf'], columns=df['aft'])

aft   0   1
bf
0    12  17
1     8  23

In [ ]:
import scipy.stats as stats

# help(stats.shapiro)



# stats.shapiro(df['aft'] - df['bf'])

ShapiroResult(statistic=0.7786344289779663, pvalue=4.1147664830987196e-08)

:

In [2]:
# 연령, 몸무게,콜레스테롤 수치 데이터

import pandas as pd 
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/28/p7.csv')
df.head(2)

   age  Cholesterol  weight
0   65         69.0   111.0
1   54        117.0    81.0